name: kupongo
description: KuponGo - AR location-based coupon hunting app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # AR Packages
  arcore_flutter_plugin: ^0.1.0  # Android AR
  arkit_plugin: ^1.0.7           # iOS AR

  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1

  # 3D & Graphics
  vector_math: ^2.1.4

  # Firebase
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.15.0

  # Networking
  http: ^1.1.0
  dio: ^5.4.0

  # State Management
  provider: ^6.1.1
  get_it: ^7.6.4

  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  lottie: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Utilities
  intl: ^0.18.1
  uuid: ^4.2.1
  equatable: ^2.0.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/models/
    - assets/sounds/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
